#!/usr/bin/env bash
#
# scripts/bump-version.sh
# scripts/bump-version.sh tool <x.y.z>
# scripts/bump-version.sh dataset <x.y.z>
#
# With no arguments, prints the current tool and dataset versions.
#
# Each version is set in one place:
#   tool     Cargo.toml's [package] version (Cargo.lock follows)
#   dataset  src/datapackage.rs's DATASET_VERSION (data/datapackage.json follows)
#
# After a bump it groups the tracked lines that still name the old version by what to do about
# them (docs examples, site data, history, other), counts the test fixtures, and prints the next
# command: after a dataset bump, the matching tool bump; after a tool bump, the CHANGELOG.md
# heading to add. Edit CHANGELOG.md yourself; scripts/release-tool.sh checks it has an entry.
#
# The two versions are linked (docs/tests.md D5): a dataset bump needs a tool bump at least as
# large, and each CHANGELOG entry names the dataset version its tool builds. Each bump prints
# the half of that rule it is about.
#
set -euo pipefail

die() { echo "✖ $*" >&2; exit 1; }
ok()  { echo "✓ $*"; }
note(){ echo "* $*"; }

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" || die "not inside a git repository"
cd "$REPO_ROOT"

CARGO_TOML="Cargo.toml"
DATASET_RS="src/datapackage.rs"
DATAPACKAGE_JSON="data/datapackage.json"
EXPECTED_KEYS="worker/test/fixtures/expected-keys.json"

tool_version() {
  # The first `version = "…"` in Cargo.toml is [package]'s.
  sed -n 's/^version = "\([^"]*\)".*/\1/p' "$CARGO_TOML" | head -1
}

dataset_version() {
  sed -n 's/^pub const DATASET_VERSION: &str = "\([^"]*\)";/\1/p' "$DATASET_RS" | head -1
}

is_semver() { [[ "$1" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; }

# major, minor or patch: the largest part that differs between two versions
bump_size() {
  local from_major from_minor to_major to_minor _
  IFS=. read -r from_major from_minor _ <<<"$1"
  IFS=. read -r to_major to_minor _ <<<"$2"
  if [[ "$from_major" != "$to_major" ]]; then echo major
  elif [[ "$from_minor" != "$to_minor" ]]; then echo minor
  else echo patch
  fi
}

# The tool version a dataset bump of this size calls for: the current tool version, bumped by
# the same part (patch → patch, minor → minor, major → major)
matching_tool_version() {
  local size="$1" major minor patch
  IFS=. read -r major minor patch <<<"$(tool_version)"
  case "$size" in
    major) echo "$((major + 1)).0.0" ;;
    minor) echo "$major.$((minor + 1)).0" ;;
    *)     echo "$major.$minor.$((patch + 1))" ;;
  esac
}

# A leftover line, cut to about 120 characters
LINE_WIDTH=120
clip() {
  if [[ ${#1} -gt $LINE_WIDTH ]]; then printf '%s…' "${1:0:LINE_WIDTH}"; else printf '%s' "$1"; fi
}

# Whether line $2 of the Rust file $1 is test code: after the file's last #[cfg(test)]. The unit
# tests are the module at the end of each file (workspace.rs also has one test-only function
# above it, which is why the last one counts).
is_unit_test_line() {
  local test_starts
  test_starts=$(grep -n -F '#[cfg(test)]' "$1" | tail -1 | cut -d: -f1)
  [[ -n "$test_starts" && "$2" -ge "$test_starts" ]]
}

# Which group a leftover falls in: history, test, site, docs or other
leftover_group() {
  local file="$1" line="$2"
  case "$file" in
    CHANGELOG.md|docs/source-issues/*) echo history ;;
    tests/*|worker/test/*)             echo test ;;
    site/src/data/*)                   echo site ;;
    docs/*|README.md|site/*)           echo docs ;;
    src/*.rs)
      if is_unit_test_line "$file" "$line"; then echo test; else echo other; fi ;;
    *) echo other ;;
  esac
}

# Prints a group's heading and its lines, if it has any
print_group() {
  local heading="$1" lines="$2" line
  [[ -n "$lines" ]] || return 0
  echo "  $heading"
  while IFS= read -r line; do printf '    %s\n' "$(clip "$line")"; done <<< "$lines"
}

report_leftovers() {
  local old="$1"
  local hits file rest line group history_files
  local docs="" site="" other="" history="" tests=0
  # The lockfiles and package.json follow their tools: nothing to review
  hits=$(git grep -n -F "$old" -- . ':!*.lock' ':!*package-lock.json' ':!*/package.json' || true)
  if [[ -z "$hits" ]]; then
    ok "No other tracked line names $old"
    return 0
  fi

  while IFS= read -r line; do
    file="${line%%:*}"
    rest="${line#*:}"
    group=$(leftover_group "$file" "${rest%%:*}")
    case "$group" in
      history) history+="$file"$'\n' ;;
      test)    tests=$((tests + 1)) ;;
      site)    site+="$line"$'\n' ;;
      docs)    docs+="$line"$'\n' ;;
      *)       other+="$line"$'\n' ;;
    esac
  done <<< "$hits"

  note "Lines that still name $old:"
  print_group "docs examples: refresh after the release is published" "${docs%$'\n'}"
  print_group "site data: regenerated by scripts/site-figures.sh" "${site%$'\n'}"
  print_group "other: review each" "${other%$'\n'}"
  if [[ -n "$history" ]]; then
    echo "  history: keep"
    history_files=$(printf '%s' "$history" | sort | uniq -c)
    while IFS= read -r line; do
      read -r count file <<<"$line"
      printf '    %s (%s line%s)\n' "$file" "$count" "$([[ "$count" == 1 ]] || echo s)"
    done <<< "$history_files"
  fi
  echo "  test fixtures: $tests line$([[ "$tests" == 1 ]] || echo s) in tests/, worker/test/ and src/ unit tests, data that names its own version"
}

update_expected_keys() {
  local before after
  before=$(shasum -a 256 "$EXPECTED_KEYS" 2>/dev/null | cut -d' ' -f1)
  UPDATE_EXPECTED_KEYS=1 cargo test --quiet --test it \
    mirror_to_ods_fyi_test::mirror_dry_run_keys_match_expected_keys_json >/dev/null
  after=$(shasum -a 256 "$EXPECTED_KEYS" 2>/dev/null | cut -d' ' -f1)
  if [[ "$before" != "$after" ]]; then
    ok "$EXPECTED_KEYS regenerated"
  else
    ok "$EXPECTED_KEYS unchanged"
  fi
}

if [[ $# -eq 0 ]]; then
  printf '%-9s%-8s%s\n' "tool" "$(tool_version)" "$CARGO_TOML"
  printf '%-9s%-8s%s\n' "dataset" "$(dataset_version)" "$DATASET_RS (DATASET_VERSION)"
  exit 0
fi

[[ $# -eq 2 ]] || die "usage: scripts/bump-version.sh [tool|dataset] <x.y.z>"
KIND="$1"
NEW="$2"
NEXT=""
is_semver "$NEW" || die "'$NEW' isn't a version. Use x.y.z, e.g. 0.2.0"

case "$KIND" in
  tool)
    OLD="$(tool_version)"
    [[ -n "$OLD" ]] || die "can't find the version in $CARGO_TOML"
    if [[ "$OLD" == "$NEW" ]]; then
      ok "tool is already $NEW"
    else
      perl -0pi -e 's/^version = "\Q'"$OLD"'\E"/version = "'"$NEW"'"/m' "$CARGO_TOML"
      [[ "$(tool_version)" == "$NEW" ]] || die "failed to set $CARGO_TOML to $NEW"
      cargo update --workspace --quiet
      ok "tool $OLD → $NEW  $CARGO_TOML, Cargo.lock"
    fi
    note "ods $NEW builds dataset $(dataset_version). CHANGELOG.md's entry for $NEW names it."
    if ! grep -qE "^## \[v?${NEW//./\\.}\]" CHANGELOG.md; then
      NEXT="Add this to CHANGELOG.md, under the title (scripts/release-tool.sh needs an entry for $NEW):
    ## [$NEW] - $(date +%F)

    Builds dataset $(dataset_version)."
    fi
    ;;
  dataset)
    OLD="$(dataset_version)"
    [[ -n "$OLD" ]] || die "can't find the version in $DATASET_RS"
    if [[ "$OLD" == "$NEW" ]]; then
      ok "dataset is already $NEW"
    else
      perl -0pi -e 's/^pub const DATASET_VERSION: &str = "\Q'"$OLD"'\E";/pub const DATASET_VERSION: &str = "'"$NEW"'";/m' "$DATASET_RS"
      [[ "$(dataset_version)" == "$NEW" ]] || die "failed to set $DATASET_RS to $NEW"
      UPDATE_SCHEMA=1 cargo test --quiet --test it schema_contract_test:: >/dev/null
      ok "dataset $OLD → $NEW  $DATASET_RS, $DATAPACKAGE_JSON"
      update_expected_keys
      note "Every Parquet file built from now on carries the new version, so every manifest digest changes."
      note "A dataset bump needs a tool bump at least as large: patch → patch, minor → minor, major → major. This is a $(bump_size "$OLD" "$NEW") bump."
      NEXT="Bump the tool to match:
    scripts/bump-version.sh tool $(matching_tool_version "$(bump_size "$OLD" "$NEW")")"
    fi
    ;;
  *)
    die "usage: scripts/bump-version.sh [tool|dataset] <x.y.z>"
    ;;
esac

if [[ "$OLD" != "$NEW" ]]; then
  report_leftovers "$OLD"
fi
if [[ -n "$NEXT" ]]; then
  echo
  echo "Next: $NEXT"
fi
